// ---------------------------
// This file was generated by Nango (v0.44.0)
// You can version this file
// ---------------------------

export interface CustomerId {
  id: string;
};

export interface Customer {
  Taxable: boolean;
  Job: boolean;
  BillWithParent: boolean;
  Balance: number;
  BalanceWithJobs: number;
  CurrencyRef: {  value: string;
  name: string;};
  PreferredDeliveryMethod: string;
  IsProject: boolean;
  domain: string;
  sparse: boolean;
  Id: string;
  SyncToken: string;
  MetaData: {  CreateTime: string;
  LastUpdatedTime: string;};
  FullyQualifiedName: string;
  DisplayName: string;
  PrintOnCheckName: string;
  Active: boolean;
  DefaultTaxCodeRef: {  value: string;};
};
